import type { ScoutItem } from "./schema";

const minutesAgo = (min: number) =>
  new Date(Date.now() - min * 60_000).toISOString();
const hoursAgo = (h: number) => minutesAgo(h * 60);
const daysAgo = (d: number) => hoursAgo(d * 24);
const daysFromNow = (d: number) =>
  new Date(Date.now() + d * 24 * 60 * 60_000).toISOString();

/**
 * 画面確認用のモックスカウト。?mock=1 で差し込まれる。
 * 全ステータス（new/read/accepted/declined/expired）を網羅。
 */
export const MOCK_SCOUTS: ScoutItem[] = [
  {
    id: "mock-1",
    subject: "【特別選考】DXコンサルタント候補としてのオファー",
    message:
      "田中様\n\n突然のご連絡失礼いたします。Global Strategy Partners 採用責任者の山田と申します。\n\nあなたのプロフィール、とりわけ大学での「製造業向けサプライチェーン最適化」プロジェクトや、学生団体でのプロジェクトリードの経験を拝見し、弊社が求める「事業課題を構造化して、テクノロジーを使い倒せる人材像」と非常に強く合致していると感じました。\n\n弊社では現在、日本の大手製造業 / 金融機関を中心に、AI / データドリブン経営への変革支援を本格化しています。今回はその中核を担う DX コンサルタント候補として、書類選考・1次選考を免除した特別選考ルートでのご案内です。\n\nまずは弊社代表 / シニアパートナーとの 30 分のカジュアル面談（オンライン可）からスタートできればと思います。あなたが今興味を持っているテーマや将来のキャリア観を伺いつつ、私たちが提供できる環境について率直にお話しさせてください。\n\nご検討のほど、何卒よろしくお願いいたします。",
    sentAt: hoursAgo(3),
    expiresAt: daysFromNow(14),
    status: "new",
    isFavorite: true,
    senderName: "山田 一郎（採用統括 / シニアマネージャー）",
    company: {
      name: "Global Strategy Partners",
      logoUrl: null,
      industry: "コンサルティング",
      description:
        "世界 30 拠点以上に展開する、デジタル戦略・データ活用に強みを持つブティックコンサルティングファーム。日本では大手製造業・金融機関・公共領域のクライアントを中心に、経営戦略の立案から AI / SaaS 導入の実装支援まで一気通貫で提供しています。創業以来「クライアントと共に意思決定をする」ことを掲げ、若手にも早期から裁量を与える育成方針です。",
      employeeCountRange: "500-1,000名",
      culture:
        "成果主義と心理的安全性を両立。20 代でも実力次第で大型プロジェクトのリード（PM）を任され、提案・採用・社内 R&D まで横断的に関わることができます。海外オフィスとのジョイントケースが日常的にあり、社内では週次の勉強会・四半期ごとのオフサイト・1on1 文化が根付いています。服装・働く時間・場所は本人裁量。OKR で目標を定め、評価は半期ごとの 360 度フィードバックで透明に決まります。",
      websiteUrl: "https://example-gsp.com",
    },
    job: {
      title: "DX コンサルタント（新卒 / 2027年卒）",
      description:
        "大手企業の経営層と並走しながら、デジタル変革テーマの構想策定 → 要件定義 → PoC 推進 → スケール実装までを一気通貫で支援するポジションです。\n\n初期 6 ヶ月は先輩コンサルタントの下で議事録・分析・資料作成を通じて型を学び、その後はサブモジュールのオーナーとしてクライアント窓口を任されます。1〜2 年目から海外オフィスのプロジェクトに参画する社員も多く、AI / データプラットフォーム / SaaS 導入など、テーマは流動的に選べます。\n\n単なる戦略提案で終わらず、クライアントの組織に入り込んで「動くものを作る」ところまで踏み込めるのが当社の特徴です。",
      requirements:
        "2027 年 3 月卒業見込み（学部 / 修士いずれも歓迎）\n論理的思考力と、仮説 → 検証のサイクルを楽しめる思考体力\nExcel / SQL / BI ツール（Looker, Tableau 等）いずれかでの定量分析経験\nクライアントの経営層に対面・オンラインで提案できるコミュニケーション力\nPython / R 等を用いた分析、または Web プロダクトの開発経験があれば尚可\nTOEIC 730 点相当以上、または英語ドキュメントを抵抗なく読める方\n長期インターン・研究・学生団体などで「成果を出した」具体的なエピソードがある方",
      benefits:
        "完全週休二日制 / 年間休日 125 日 / 有給取得率 90%超\nフルフレックス + リモートワーク（コアタイムなし）\n書籍・カンファレンス費用 月 3 万円まで会社負担\n海外オフィス短期派遣制度（入社 2 年目以降、選考あり）\n社内 MBA 制度・外部講師招聘の月次ワークショップ\n副業可（守秘義務とコンフリクトチェックのみ実施）\n社員紹介の家族・パートナー向けイベントを四半期ごとに開催",
      jobType: "コンサルタント / DX",
      jobCategory: "コンサルティング",
      heroImageUrl:
        "https://images.unsplash.com/photo-1556761175-b413da4baf72?w=1200&h=400&fit=crop&auto=format",
      workLocation: "東京本社（丸の内）/ リモート可（出社は週 1 程度の任意ベース）",
      employmentType: "正社員（新卒）",
      salaryRange: "年収 550 〜 800 万円（経験・能力を考慮、四半期ごとの業績連動賞与あり）",
      targetGraduationYears: [2027, 2028],
    },
  },
  {
    id: "mock-2",
    subject: "サマーインターンシップのご案内",
    message:
      "弊社のサマーインターンシッププログラムにあなたをご招待します。金融業界におけるデジタルトランスフォーメーションの最前線を体験できるプログラムです。",
    sentAt: daysAgo(2),
    expiresAt: daysFromNow(7),
    status: "read",
    isFavorite: false,
    senderName: "田中 健太",
    company: {
      name: "Heritage Financial Group",
      logoUrl: null,
      industry: "金融",
      description:
        "創業100年を超える総合金融グループ。近年はフィンテック領域にも積極投資しています。",
      employeeCountRange: "10,000名以上",
      culture:
        "100年企業ならではの安定基盤を活かしつつ、新規事業ラボでは少人数の機動的な編成で挑戦を奨励。研修制度と評価制度が整っています。",
      websiteUrl: "https://example-heritage.com",
    },
    job: {
      title: "サマーインターン（アナリスト職）",
      description: "5日間の実践プログラムで現場アナリスト業務を体験します。",
      requirements:
        "2026 or 2027年卒の学生\n金融・経済への強い関心\nExcel / スプレッドシートでの基礎的なデータ操作\n英語力（TOEIC 750 程度以上が望ましい）",
      benefits: "交通費全額支給 / 昼食支給 / 優秀者は早期選考招待",
      jobType: "アナリスト",
      jobCategory: "金融",
      workLocation: "東京本社（大手町）",
      employmentType: "インターン（5日間）",
      salaryRange: "日給 10,000 円 + 交通費",
      targetGraduationYears: [2027, 2028],
    },
  },
  {
    id: "mock-3",
    subject: "【最終確認】カジュアル面談の日程について",
    message:
      "カジュアル面談の日程についてご確認いただきありがとうございました。確定したのでご連絡いたします。",
    sentAt: daysAgo(4),
    expiresAt: null,
    status: "accepted",
    isFavorite: true,
    senderName: "佐々木 美咲",
    company: {
      name: "Nexus Systems Inc.",
      logoUrl: null,
      industry: "IT・インターネット",
      description: "B2B SaaS のリーディングカンパニー。",
      employeeCountRange: "100-500名",
      culture:
        "プロダクト主導のフラットな組織。週 1 のシップ会で開発成果を全員で共有し、エンジニア比率は 60% 超。リモートと出社を本人が選べます。",
      websiteUrl: "https://example-nexus.com",
    },
    job: {
      title: "プロダクトエンジニア",
      description: "自社プロダクトのフルスタック開発に携わります。",
      requirements:
        "個人 / 業務での Web アプリ開発経験（React / Next.js 推奨）\nTypeScript の基礎\nGit を使った共同開発経験\n長期インターンや個人開発での継続的なアウトプットがあると尚可",
      benefits: "フレックスタイム / リモート可 / ストックオプション",
      jobType: "ソフトウェアエンジニア / フルスタック",
      jobCategory: "IT・インターネット",
      heroImageUrl:
        "https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=1200&h=400&fit=crop&auto=format",
      workLocation: "東京（渋谷）/ リモート可",
      employmentType: "正社員",
      salaryRange: "年収 600〜900 万円",
      targetGraduationYears: [],
    },
  },
  {
    id: "mock-4",
    subject: "秋採用本選考のご案内",
    message:
      "お忙しいところ恐れ入ります。弊社の秋採用本選考についてご案内いたします。書類選考を免除し、一次面接からのスタートが可能です。",
    sentAt: daysAgo(7),
    expiresAt: null,
    status: "declined",
    isFavorite: false,
    senderName: "鈴木 健吾",
    company: {
      name: "Aurora Capital",
      logoUrl: null,
      industry: "金融",
      description: "成長企業向けのグロースキャピタル。",
      employeeCountRange: "50-100名",
      culture: null,
      websiteUrl: "https://example-aurora.com",
    },
    job: {
      title: "インベストメントアナリスト",
      description: "投資先候補の事業評価・デューデリジェンスを担当。",
      requirements: null,
      benefits: "成果報酬 / 海外研修制度",
      jobType: "インベストメントアナリスト",
      jobCategory: "金融",
      workLocation: "東京（六本木）",
      employmentType: "正社員（新卒）",
      salaryRange: "年収 650〜900 万円",
      targetGraduationYears: [2027, 2028],
    },
  },
  {
    id: "mock-5",
    subject: "プラチナスカウト: 事業開発リードポジション",
    message:
      "プラチナ枠でのスカウトをお送りいたします。新規事業立ち上げに携われるポジションです。",
    sentAt: daysAgo(30),
    expiresAt: daysAgo(2),
    status: "expired",
    isFavorite: false,
    senderName: "高橋 さくら",
    company: {
      name: "Vanguard Robotics",
      logoUrl: null,
      industry: "製造業",
      description: "自律移動ロボットの開発を行うディープテック企業。",
      employeeCountRange: "100-500名",
      culture: null,
      websiteUrl: "https://example-vanguard.com",
    },
    job: {
      title: "事業開発リード候補",
      description: "新規事業の立ち上げから収益化までをリードします。",
      requirements: null,
      benefits: "裁量大 / ストックオプション / 出社・リモート選択可",
      jobType: "事業開発 / BizDev",
      jobCategory: "製造業",
      workLocation: "東京（品川）/ リモート併用",
      employmentType: "正社員",
      salaryRange: "年収 700〜1,100 万円",
      targetGraduationYears: [],
    },
  },
  {
    id: "mock-6",
    subject: "エンジニアポジションへのスカウト",
    message:
      "あなたの技術ブログを拝見しました。弊社のフロントエンドチームと相性が良さそうです。",
    sentAt: hoursAgo(20),
    expiresAt: daysFromNow(10),
    status: "new",
    isFavorite: true,
    senderName: "伊藤 翔太",
    company: {
      name: "Lumina Labs",
      logoUrl: null,
      industry: "IT・インターネット",
      description: "LLM アプリケーションを開発するシードスタートアップ。",
      employeeCountRange: "10-50名",
      culture: null,
      websiteUrl: "https://example-lumina.com",
    },
    job: {
      title: "フロントエンドエンジニア（新卒）",
      description: "React / Next.js を使った AI プロダクト開発。",
      requirements: null,
      benefits: "リモートフルリモート / 裁量労働制",
      jobType: "ソフトウェアエンジニア / フロントエンド",
      jobCategory: "IT・インターネット",
      workLocation: "フルリモート（全国可）",
      employmentType: "正社員（新卒）",
      salaryRange: "年収 500〜720 万円",
      targetGraduationYears: [2027, 2028],
    },
  },
  {
    id: "mock-7",
    subject: "グロースマーケターポジションへのオファー",
    message:
      "SNS での発信内容を拝見しました。弊社が立ち上げる新規プロダクトのグロース施策をリードいただける方を探しています。",
    sentAt: minutesAgo(45),
    expiresAt: daysFromNow(21),
    status: "new",
    isFavorite: false,
    senderName: "中村 優",
    company: {
      name: "Beacon Marketing",
      logoUrl: null,
      industry: "広告・マーケティング",
      description: "D2C ブランドのグロース支援を行う専門ファーム。",
      employeeCountRange: "50-100名",
      culture: null,
      websiteUrl: "https://example-beacon.com",
    },
    job: {
      title: "グロースマーケター（新卒）",
      description: "D2C クライアントの SNS / 広告運用を担当。",
      requirements: null,
      benefits: "成果報酬 / フレックスタイム / 副業可",
      jobType: "マーケター / グロース",
      jobCategory: "広告・マーケティング",
      workLocation: "東京（表参道）/ リモート可",
      employmentType: "正社員（新卒）",
      salaryRange: "年収 450〜650 万円 + 成果報酬",
      targetGraduationYears: [2027, 2028],
    },
  },
  {
    id: "mock-8",
    subject: "プロダクトマネージャー新卒採用のご案内",
    message:
      "あなたの企画コンテスト受賞歴に注目しています。弊社の新規プロダクトの PdM 候補としてご応募を検討いただけませんか。",
    sentAt: hoursAgo(9),
    expiresAt: daysFromNow(14),
    status: "new",
    isFavorite: false,
    senderName: "小林 遥",
    company: {
      name: "Orbit Works",
      logoUrl: null,
      industry: "IT・インターネット",
      description: "働き方データを扱う SaaS スタートアップ。",
      employeeCountRange: "50-100名",
      culture: null,
      websiteUrl: "https://example-orbit.com",
    },
    job: {
      title: "プロダクトマネージャー候補（新卒）",
      description: "プロダクトの企画から開発までを横断的にリード。",
      requirements: null,
      benefits: "リモート可 / ストックオプション",
      jobType: "プロダクトマネージャー",
      jobCategory: "IT・インターネット",
      workLocation: "東京（恵比寿）/ フルリモート可",
      employmentType: "正社員（新卒）",
      salaryRange: "年収 480〜700 万円",
      targetGraduationYears: [2027, 2028],
    },
  },
  {
    id: "mock-9",
    subject: "データサイエンティスト新卒ポジション",
    message:
      "Kaggle のコンペ履歴を拝見しました。弊社のレコメンデーションチームに即戦力として加わっていただけないでしょうか。",
    sentAt: daysAgo(1),
    expiresAt: daysFromNow(9),
    status: "new",
    isFavorite: false,
    senderName: "松本 大輔",
    company: {
      name: "Helios Analytics",
      logoUrl: null,
      industry: "IT・インターネット",
      description: "大手小売チェーン向けデータ基盤を提供。",
      employeeCountRange: "100-500名",
      culture: null,
      websiteUrl: "https://example-helios.com",
    },
    job: {
      title: "データサイエンティスト（新卒）",
      description: "購買データを活用したレコメンドモデルの開発。",
      requirements: null,
      benefits: "論文発表支援 / 学会参加支援",
      jobType: "データサイエンティスト",
      jobCategory: "IT・インターネット",
      workLocation: "東京（中野）/ 週2 リモート",
      employmentType: "正社員（新卒）",
      salaryRange: "年収 550〜800 万円",
      targetGraduationYears: [2027, 2028],
    },
  },
  {
    id: "mock-10",
    subject: "営業リーダー候補 新卒採用",
    message:
      "学生時代のインターン成果を拝見しました。弊社のエンタープライズ営業チームでキャリアを築きませんか。",
    sentAt: minutesAgo(10),
    expiresAt: daysFromNow(28),
    status: "new",
    isFavorite: false,
    senderName: "大塚 誠",
    company: {
      name: "Summit Sales",
      logoUrl: null,
      industry: "IT・インターネット",
      description: "エンタープライズ向けセールステック SaaS。",
      employeeCountRange: "100-500名",
      culture: null,
      websiteUrl: "https://example-summit.com",
    },
    job: {
      title: "エンタープライズ営業（新卒）",
      description: "中堅〜大手企業向けの課題ヒアリングと提案営業。",
      requirements: null,
      benefits: "インセンティブ制度 / MVP 表彰 / リモート可",
      jobType: "法人営業 / カスタマーサクセス",
      jobCategory: "IT・インターネット",
      workLocation: "東京本社（汐留）/ リモート併用",
      employmentType: "正社員（新卒）",
      salaryRange: "年収 480〜700 万円 + インセンティブ",
      targetGraduationYears: [2027, 2028],
    },
  },
  {
    id: "mock-11",
    subject: "UI/UX デザイナー 新卒採用",
    message:
      "ポートフォリオのインタラクションデザインに感銘を受けました。ぜひカジュアル面談の機会をいただけますか。",
    sentAt: hoursAgo(12),
    expiresAt: daysFromNow(20),
    status: "new",
    isFavorite: true,
    senderName: "青木 美穂",
    company: {
      name: "Crafted Studio",
      logoUrl: null,
      industry: "サービス",
      description: "DXクライアントのプロダクトデザインを専門に支援。",
      employeeCountRange: "10-50名",
      culture: null,
      websiteUrl: "https://example-crafted.com",
    },
    job: {
      title: "UI/UX デザイナー（新卒）",
      description: "複数プロジェクトでのプロトタイピング・ユーザーテストに従事。",
      requirements: null,
      benefits: "書籍購入補助 / カンファレンス参加支援",
      jobType: "デザイナー / UI・UX",
      jobCategory: "サービス",
      workLocation: "東京（神楽坂）/ リモート可",
      employmentType: "正社員（新卒）",
      salaryRange: "年収 420〜600 万円",
      targetGraduationYears: [2027, 2028],
    },
  },
  {
    id: "mock-12",
    subject: "サステナビリティ戦略担当 候補",
    message:
      "環境系プロジェクトでの発表を拝見しました。弊社の ESG 領域でのキャリアをご一緒できればと考えています。",
    sentAt: hoursAgo(5),
    expiresAt: daysFromNow(30),
    status: "new",
    isFavorite: false,
    senderName: "白石 亮",
    company: {
      name: "Verdant Advisory",
      logoUrl: null,
      industry: "コンサルティング",
      description: "企業のサステナビリティ戦略を支援する専門ファーム。",
      employeeCountRange: "50-100名",
      culture: null,
      websiteUrl: "https://example-verdant.com",
    },
    job: {
      title: "サステナビリティアナリスト（新卒）",
      description: "クライアント企業の ESG レポート作成と戦略策定を支援。",
      requirements: null,
      benefits: "海外プロジェクト参加機会 / 副業可",
      jobType: "コンサルタント / ESG",
      jobCategory: "コンサルティング",
      workLocation: "東京（虎ノ門）",
      employmentType: "正社員（新卒）",
      salaryRange: "年収 500〜720 万円",
      targetGraduationYears: [2027, 2028],
    },
  },
];
