name: Sync to personal repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Debug token
        run: |
          if [ -z "${{ secrets.PERSONAL_REPO_TOKEN }}" ]; then
            echo "TOKEN EMPTY"
            exit 1
          else
            echo "TOKEN OK"
          fi

      - name: Push to personal repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git remote remove mirror || true
          git remote add mirror https://x-access-token:${{ secrets.PERSONAL_REPO_TOKEN }}@github.com/gakuhi/scout-vercel-deploy-repo.git

          git push mirror HEAD:main --force
