name: Sync to personal repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Debug token
        run: |
          if [ -z "${{ secrets.PERSONAL_REPO_TOKEN }}" ]; then
            echo "TOKEN EMPTY"
            exit 1
          else
            echo "TOKEN OK"
          fi
      - name: Push to personal repo
        run: |
          git remote add mirror https://x-access-token:${{ secrets.PERSONAL_REPO_TOKEN }}@github.com/gakuhi/scout-vercel-deploy-repo.git
          git push mirror main --force


